vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/webroot/uploads/coursesfiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer