version: '3.9'
 
services:
    db:
        container_name: mysql-server 
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=dockerizeme_db
            - MYSQL_USER=someuser
        volumes:
            - dbdata:/var/lib/mysql

    web:
        build: .
        ports:
            - 8001:80
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db

    mercure:
        image: dunglas/mercure
        ports:
        - "80"

volumes:
  dbdata:   

###> symfony/mercure-bundle ###

###< symfony/mercure-bundle ###


