framework:

  http_client:
    default_options:
      verify_peer: false

  session:
      handler_id: null
      cookie_secure: false
      cookie_samesite: 'lax'
      storage_factory_id: session.storage.factory.native